{
 "title": "growbox",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "leaf RH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "humidity{sensor=\"htu21d\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "humidity",
     "measurement": "growbox_rh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature{sensor=\"htu21d\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "ambient",
     "measurement": "growbox_temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expr": "object_temperature", "legendFormat": "leaf" }
   ]
  },
  {
   "title": "soil moisture",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "soil_moisture{sensor=\"soil12\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "moisture",
     "measurement": "growbox_soil_moisture",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VPD",
   "type": "timeseries",
   "description": "https://www.dimluxlighting.com/wp-content/uploads/2019/02/Leaf-Vapor-Pressure-Deficit-VPD-5.jpg.webp",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    {
     "expr": "vpd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "vpd",
     "measurement": "growbox_vpd",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "vpd vs soil moisture change rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "sum(delta(soil_moisture[60m]))", "legendFormat": "moisture update rate" },
    { "expr": "vpd", "legendFormat": "vpd" }
   ]
  },
  {
   "title": "leaf vs ambient temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(object_temperature)-sum(temperature{sensor=\"htu21d\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}